### PR TITLE
Added support for file_get_contents if curl is not available

### PR DESCRIPTION
**Pull request by troykelly**
Hackery to get this to work inside of Google App Engine

### CODE REVIEW

**Comment by troykelly** [comment]
I am using this inside of Google App Engine - which does not (easily) expose curl. This is working but not thoroughly tested.

**Comment by khurshid-alam** [comment]
Travis check failed for your code.

**Comment by troykelly** [comment]
I see that. Yet, it works. Any ideas?

**Comment by J7mbo** [comment]
Travis shows:

> PHP Parse error:  syntax error, unexpected '[' in /home/travis/build/J7mbo/twitter-api-php/TwitterAPIExchange.php on line 322

Short array syntax (`[]`), but this is backwards compatible with < PHP 5.4.

Also this is a pretty massive change, the PR needs to go into `development` branch but I also think there'll need to be a good amount of tests to prove this works alongside the change.

**Comment by troykelly** [comment]
I just thought I'd share it with you, it's a quick hack just to get this working in App Engine without curl.

**Comment by J7mbo** [comment]
Thanks for this. I know it's an old one although I think it's awesome. I'm just going through and cleaning things up, removing the cURL requirement would be great. 

It's a PR into master at the moment, and it needs to be in develop and pass tests.

I'll bear it in mind and put it as a feature, maybe work on it myself and put a thanks to you in it. Closing for now though as doesn't pass tests etc, cheers.

**Comment by troykelly** [comment]
No problem. We've moved away from PHP to NodeJS a lot of stuff, so I haven't really looked at this again I'm sorry.

**Pull request closed without merging**
