### PR TITLE
CURLOPT_SSL_VERIFYPEER => false

### PR DESCRIPTION
**Pull request by peter-mw**
The response is empty on XAMPP, setting this option fixes it

### CODE REVIEW

**Comment by J7mbo** [comment]
Please see #14.

**Comment by peter-mw** [comment]
Hi, yes but its still not merged in master https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L192

**Comment by J7mbo** [comment]
That's because I don't want to open up the code to man in the middle attacks. The reason it's not working in windows is because you haven't got cURL certificates set up properly. Check [this thread](https://github.com/J7mbo/twitter-api-php/issues/21#issuecomment-23699461) for more info that I think you may find useful.

**Comment by peter-mw** [comment]
hehe :) if i have man in the middle attack i would have much bigger problems than reading from my twitter feed, which you can read anyway

**Comment by J7mbo** [comment]
Imagine if you have your twitter api client set to read AND write. It's just dangerous to enable that option. If you set up your certs right, that might help you.

**Pull request closed without merging**
