### PR TITLE
Allow overriding of curl options

### PR DESCRIPTION
**Pull request by emmetog**
This was causing a problem because even if the user specified a curl option it was ignored because the value in the "defaults array" overrode it.

> If you want to append array elements from the second array to the first array while not overwriting the elements from the first array and not re-indexing, use the + array union operator. The keys from the first array will be preserved. If an array key exists in both arrays, then the element from the first array will be used and the matching key's element from the second array will be ignored.
http://php.net/manual/en/function.array-merge.php

### CODE REVIEW

**Comment by emmetog** [comment]
Fixes https://github.com/J7mbo/twitter-api-php/issues/160

**Comment by emmetog** [comment]
PHPUnit tests run fine on my local machine, @J7mbo any ideas why it's failing?

**Comment by J7mbo** [comment]
Can you make this into `develop` branch please?

**Comment by emmetog** [comment]
@J7mbo Here's the new PR https://github.com/J7mbo/twitter-api-php/pull/204.

Closing this

**Pull request closed without merging**
