### PR TITLE
Readme: simplify composer install

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by J7mbo** [comment]
Thanks for the PR! :-)

**Comment by TomasVotruba** [comment]
Changed.

I recommend making the dev branch as default one, since it's common to send PR against it.

**Comment by TomasVotruba** [comment]
Ping?

**Comment by J7mbo** [comment]
Boom! Sorry for the delay 😅

**Comment by TomasVotruba** [comment]
Thank you! :)

**Pull request merged**
