### PR TITLE
travis: add more recent PHP versions

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by J7mbo** [comment]
Thanks for the PR! The [platform constraints](https://getcomposer.org/doc/01-basic-usage.md#package-version-constraints) could probably be simplified to `>= 5.3` rather than a list we'd have to update all the time.

If you change that, 1 commit, into dev branch, I'll be happy to merge.

**Comment by TomasVotruba** [comment]
This is `travis.yml`, not `composer.json`. I think it works different

Also this is first of few commits I plan to add

**Comment by J7mbo** [comment]
Ah, I missed this travis part and thought it was composer. Thanks! Also, please put this onto the dev branch! :)

**Comment by TomasVotruba** [comment]
Sure.  Could you set dev it as default to prevent this in the future?

How do they actually differ? Looks like they have same activity.

**Comment by TomasVotruba** [comment]
Not relevant anymore. I'm closing to clean my opened PRs.

Feel free to cherry pick anything you need.

**Pull request closed without merging**
