### PR TITLE
[read me] - update twitter api docs links

### PR DESCRIPTION
**Pull request by CHEWX**
Hi,

Your doc links 404, have updated for new people coming to view.

Thanks,
Tom

### CODE REVIEW

**Comment by Nickfost** [comment]
Please accept!

**Comment by khurshid-alam** [comment]
Check failed!!

**Comment by CHEWX** [comment]
@khurshid-alam I pull requested documentation changes. The build in it's current state fails!

Pull request with zero changes, it will fail.

I guess this is another Open Source project that will get left behind.

**Review by pau1phi11ips — APPROVED** [review]

**Comment by J7mbo** [comment]
This needs to go into develop branch :)

**Comment by CHEWX** [comment]
Looks as is @pau1phi11ips has done this for me then... https://github.com/J7mbo/twitter-api-php/pull/231

When are you going to merge into `master` as users won't know to clone or download from the `develop` branch. @J7mbo

**Comment by J7mbo** [comment]
Btw: Develop has now merged into master. Thanks everyone for being patient :-)

**Pull request closed without merging**
